// Regenerates the PRESETS block in index.html from the original C++ data.
// Usage: node convert_data.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const SRC = "/Users/neoneye/git/opcoders_toolbox/CONTENT/TBEngine/brick_lib/gfx_chaos_data.cpp";
const here = dirname(fileURLToPath(import.meta.url));
let cpp = readFileSync(SRC, "utf8");
// Strip comments before parsing. Block comments can sit inside definitions
// (e.g. func21 "Koch curve" has a commented-out coefficient table). Line
// comments are stripped only when preceded by whitespace so the http://
// URLs inside preset name strings survive.
cpp = cpp.replace(/\/\*[\s\S]*?\*\//g, "").replace(/(^|\s)\/\/[^\n]*/g, "$1");

// 1. Parse every FunctionData definition: identifier, name, set count, floats.
const defs = new Map();
const defRe = /FunctionData\s+(\w+)\s*=\s*\{\s*"([^"]*)"\s*,\s*(\d+)\s*,([^;]*?)\};/gs;
let m;
while ((m = defRe.exec(cpp))) {
  const [, ident, name, countStr, body] = m;
  const count = Number(countStr);
  const nums = (body.match(/-?\d+\.?\d*(?:[eE][-+]?\d+)?/g) || []).map(Number);
  if (nums.length < count * 7) {
    throw new Error(`${ident}: expected ${count * 7} numbers, found ${nums.length}`);
  }
  const maps = [];
  for (let i = 0; i < count; i++) maps.push(nums.slice(i * 7, i * 7 + 7));
  defs.set(ident, { name, maps });
}

// 2. Parse the fdata[] array, honoring #if 1 / #if 0 blocks.
const fdataBody = cpp.match(/const FunctionData fdata\[\]\s*=\s*\{([\s\S]*?)\};/)[1];
const order = [];
let active = true;
for (const line of fdataBody.split("\n")) {
  const t = line.trim();
  if (t.startsWith("#if")) { active = t === "#if 1"; continue; }
  if (t.startsWith("#endif")) { active = true; continue; }
  if (!active || t.startsWith("//")) continue;
  for (const ident of t.split(",").map((s) => s.trim()).filter(Boolean)) {
    if (!defs.has(ident)) throw new Error(`fdata references unknown ${ident}`);
    order.push(ident);
  }
}

const presets = order.map((ident) => defs.get(ident));
const json = presets.map((p) =>
  `{name:${JSON.stringify(p.name)},maps:[${p.maps.map((row) => `[${row.join(",")}]`).join(",")}]}`
).join(",\n");

// 3. Splice between markers in index.html.
const htmlPath = join(here, "index.html");
const html = readFileSync(htmlPath, "utf8");
const out = html.replace(
  /\/\/ BEGIN GENERATED PRESETS[\s\S]*?\/\/ END GENERATED PRESETS/,
  `// BEGIN GENERATED PRESETS\n// Generated by convert_data.mjs from gfx_chaos_data.cpp — do not edit.\nconst PRESETS = [\n${json}\n];\n// END GENERATED PRESETS`
);
writeFileSync(htmlPath, out);
console.log(`Wrote ${presets.length} presets.`);
