"""Generate the high-precision trigonometric oracle used by
tiling_rigorous_test.js.  NOT in the trusted base and not run by the suite:
this writes tiling_trig.oracle.json, which is committed, and the suite checks
the JavaScript enclosures against it.

    python3 -m venv venv && venv/bin/pip install mpmath
    venv/bin/python tiling_trig_oracle.py

The point of an oracle rather than a comparison against the engine's own
Math.sin is independence: tiling_rigorous.js implements sine by Cody-Waite
reduction and a Taylor series precisely so as not to depend on Math.sin, so
validating it against Math.sin is close to circular.  mpmath at 60 digits is
a different implementation, in a different language, on a different algorithm.

Sample points are biased towards where the implementation is most delicate:

  * multiples of pi/2, and tiny offsets from them, where argument reduction
    cancels catastrophically and the Cody-Waite split has to carry the result;
  * the boundary |r| = pi/4 between the sine and cosine branches;
  * arguments out to +/-400, which covers the sinc arguments the sweep reaches
    (a pair distance of 96 gives |z| about 302);
  * the exact arguments the kernel evaluates, z = (sqrt2 +/- 2 pi x)/2, on a
    grid of x, so the oracle covers the composed path and not only sine alone;
  * the subnormal and near-zero regime, where the series branch takes over.

Each x is written with 17 significant digits, which round-trips exactly through
an IEEE double, and the test asserts that round-trip before using it.
"""
import json
from mpmath import mp, mpf, sin, cos, sqrt, pi

mp.dps = 60

def points():
    out = []
    half = pi / 2
    for k in range(-160, 161):
        base = k * half
        for delta in ('0', '1e-15', '-1e-15', '1e-8', '-1e-8', '1e-3', '-1e-3'):
            out.append(base + mpf(delta))
    quarter = pi / 4
    for k in range(-40, 41):
        for delta in ('0', '1e-12', '-1e-12', '1e-6', '-1e-6'):
            out.append(k * pi + quarter + mpf(delta))
            out.append(k * pi - quarter + mpf(delta))
    for e in range(-320, 1, 8):
        out.append(mpf(10) ** e)
        out.append(-(mpf(10) ** e))
    # the composed path: kernel arguments z = (sqrt2 +/- 2 pi x)/2
    for i in range(0, 1200):
        x = mpf(i) * mpf('0.08')
        out.append((sqrt(2) - 2 * pi * x) / 2)
        out.append((sqrt(2) + 2 * pi * x) / 2)
    seed = mpf(1)
    for i in range(1200):
        seed = (seed * 1103515245 + 12345) % 2147483648
        out.append((seed / 2147483648 - mpf('0.5')) * 800)
    return out

rows = []
seen = set()
for value in points():
    x = float(value)                      # the double the test will actually use
    if not (-1e5 < x < 1e5):
        continue
    if x in seen:
        continue
    seen.add(x)
    xs = repr(x)
    # mpf(float) is an exact binary-to-binary conversion; mpf(str) would parse
    # the DECIMAL, which differs from the double by up to half an ulp -- about
    # 4e-14 at |x| ~ 400, which is larger than the enclosures being tested and
    # would make every large-argument row a spurious failure.  (It did.)
    xm = mpf(x)
    rows.append([xs, mp.nstr(sin(xm), 40), mp.nstr(cos(xm), 40)])

json.dump({
    'note': 'sin and cos at 60-digit precision, evaluated at the exact double '
            'each x string denotes -- via mpf(float), never mpf(str). Generated by tiling_trig_oracle.py; see its '
            'docstring for why the sample is biased the way it is.',
    'digits': 40,
    'count': len(rows),
    'rows': rows,
}, open('tiling_trig.oracle.json', 'w'))
print('wrote', len(rows), 'oracle rows')
